#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=99
USE_PROCD=1
PROG=/usr/bin/geolocate-daemon

start_service() {
	local enabled
	config_load geolocate
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
	procd_set_param file /etc/config/geolocate
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "geolocate"
}
